/**
 * @file spirv_registry.h
 * @brief SPIR-V blob registry — domain libraries register their
 *        compiled shaders here (generated by the shaders/ CMake
 *        subproject into a constexpr byte array per shader), then
 *        look them up by canonical name at pipeline-build time.
 */
#ifndef BR_CORE_SPIRV_REGISTRY_H
#define BR_CORE_SPIRV_REGISTRY_H

#include <cstdint>
#include <string_view>
#include <unordered_map>
#include <vector>

namespace br_core {

struct SpirvBlob {
    const std::uint32_t* words;
    std::uint32_t        word_count;
};

class SpirvRegistry {
public:
    /** Register a SPIR-V blob. @p name must outlive the registry. */
    void register_blob(std::string_view name, const std::uint32_t* words, std::uint32_t word_count);

    /** Returns {nullptr, 0} when no such blob exists. */
    SpirvBlob lookup(std::string_view name) const;

    std::size_t size() const { return blobs_.size(); }

    /** Register a blob into a static queue before Core is initialized. */
    static void add_deferred_blob(const char* name, const std::uint32_t* words, std::uint32_t word_count);

    /** Called by Core during bring_up to consume the static queue. */
    void consume_deferred();

private:
    // Hash keyed by string_view; values are borrowed pointers into
    // the generated constexpr arrays — no copy.
    std::unordered_map<std::string, SpirvBlob> blobs_;
};

} // namespace br_core

#endif // BR_CORE_SPIRV_REGISTRY_H
