"""
Training script for FNOFluid3D — BIFROST fluid surrogate model.

Trains the FNOFluid3D architecture on NS reference trajectories generated by
brml.data.ns_reference_solver, then exports to bifrost_fluid.onnx.

The exported model satisfies BIFROSTModelRegistry contract:
  model_id:  "bifrost_fluid"
  input:     float32 [1, N, N, N, 8]  (vx,vy,vz,p,rho,vof,typeOcc,phi) — normalized
  output:    float32 [1, N, N, N, 4]  (vx_next,vy_next,vz_next,p_next) — normalized
  N:         grid_size (default 40 = 4 blocks × SUB=10)

Usage:
  # Generate training data first:
  python -m brml.data.ns_reference_solver --out ./data/fluid --n-traj 2000

  # Train and export:
  python -m brml.train.train_fnofluid --data-dir ./data/fluid --steps 100000
  python -m brml.train.train_fnofluid --data-dir ./data/fluid --steps 50000 --fast

  # Export only (resume from checkpoint):
  python -m brml.train.train_fnofluid --export-only --ckpt ./checkpoints/fluid_best.pkl
"""
from __future__ import annotations

import argparse
import os
import glob
import time
from pathlib import Path
from typing import Iterator

import numpy as np

try:
    import jax
    import jax.numpy as jnp
    import optax
    import flax.linen as nn
    from flax.training import train_state
    import orbax.checkpoint as ocp
    _FULL_DEPS = True
except ImportError:
    _FULL_DEPS = False

from brml.models.fno_fluid import FNOFluid3D

# ─── Normalization constants (must match OnnxFluidRuntime.java) ───────────────
V_SCALE   = 10.0
P_SCALE   = 101325.0
RHO_SCALE = 1000.0
PHI_SCALE = 101325.0

# ─── Training hyper-parameters ────────────────────────────────────────────────
DEFAULT_LR          = 1e-3
DEFAULT_WEIGHT_DECAY = 1e-4
SCHEDULER_DECAY_RATE = 0.5       # LR halved every DECAY_STEPS
SCHEDULER_DECAY_STEPS = 20_000
BATCH_SIZE          = 4          # trajectories per gradient step
GRID_SIZE           = 40         # sub-cell grid N (must match ns_reference_solver)


# ─── Dataset loader ──────────────────────────────────────────────────────────

def _shard_paths(data_dir: str) -> list[str]:
    paths = sorted(glob.glob(os.path.join(data_dir, "fluid_traj_shard_*.npz")))
    if not paths:
        raise FileNotFoundError(
            f"No fluid_traj_shard_*.npz found in {data_dir}. "
            "Run: python -m brml.data.ns_reference_solver --out " + data_dir)
    return paths


def _iter_batches(data_dir: str, batch_size: int,
                  rng: np.random.Generator) -> Iterator[tuple[np.ndarray, np.ndarray]]:
    """Infinite iterator over (inputs, targets) batches from .npz shards.

    Shapes:
      inputs:  [B, N, N, N, 8]  (one random t per trajectory)
      targets: [B, N, N, N, 4]
    """
    paths = _shard_paths(data_dir)
    while True:
        rng.shuffle(paths)
        for shard_path in paths:
            data = np.load(shard_path)
            inp  = data['inputs']   # [B_shard, T, N, N, N, 8]
            out  = data['outputs']  # [B_shard, T, N, N, N, 4]
            B_shard, T = inp.shape[:2]

            # Pick a random time step per trajectory
            t_idx = rng.integers(0, T, size=B_shard)
            inp_flat = inp[np.arange(B_shard), t_idx]   # [B_shard, N, N, N, 8]
            out_flat = out[np.arange(B_shard), t_idx]   # [B_shard, N, N, N, 4]

            # Yield mini-batches
            idx = np.arange(B_shard)
            rng.shuffle(idx)
            for start in range(0, B_shard, batch_size):
                sl = idx[start:start + batch_size]
                if len(sl) < batch_size:
                    break
                yield inp_flat[sl], out_flat[sl]


# ─── Loss function ────────────────────────────────────────────────────────────

def _loss_fn(params, model, inputs, targets):
    """MSE in normalized space — weighted to emphasize velocity over pressure."""
    preds = model.apply({'params': params}, inputs)   # [B, N, N, N, 4]
    # velocity loss (channels 0-2) × 3, pressure loss (channel 3) × 1
    vel_loss = jnp.mean((preds[..., :3] - targets[..., :3]) ** 2) * 3.0
    p_loss   = jnp.mean((preds[..., 3:] - targets[..., 3:]) ** 2)
    return vel_loss + p_loss


# ─── Training loop ────────────────────────────────────────────────────────────

def train(data_dir: str, steps: int, out_dir: str,
          checkpoint_every: int = 5_000,
          eval_every: int = 1_000,
          lr: float = DEFAULT_LR,
          grid_size: int = GRID_SIZE,
          seed: int = 42) -> None:
    if not _FULL_DEPS:
        raise ImportError("JAX, Flax, Optax, and Orbax are required for training. "
                          "pip install jax flax optax orbax-checkpoint")

    rng = np.random.default_rng(seed)
    jax_rng = jax.random.PRNGKey(seed)

    model = FNOFluid3D()

    # Dummy input for parameter init
    dummy = jnp.zeros((1, grid_size, grid_size, grid_size, 8))
    jax_rng, init_rng = jax.random.split(jax_rng)
    params = model.init(init_rng, dummy)['params']

    # Cosine LR schedule
    schedule = optax.cosine_decay_schedule(lr, steps)
    optimizer = optax.adamw(schedule, weight_decay=DEFAULT_WEIGHT_DECAY)
    state = train_state.TrainState.create(
        apply_fn=model.apply, params=params, tx=optimizer)

    @jax.jit
    def train_step(state, inputs, targets):
        loss, grads = jax.value_and_grad(_loss_fn)(
            state.params, model, inputs, targets)
        state = state.apply_gradients(grads=grads)
        return state, loss

    # Checkpointing
    ckpt_dir = Path(out_dir) / "checkpoints"
    ckpt_dir.mkdir(parents=True, exist_ok=True)
    checkpointer = ocp.StandardCheckpointer()

    batch_iter = _iter_batches(data_dir, BATCH_SIZE, rng)
    best_loss = float('inf')
    t0 = time.time()

    print(f"Training FNOFluid3D: {steps} steps, grid={grid_size}³, lr={lr}")

    for step in range(1, steps + 1):
        inp_np, out_np = next(batch_iter)
        inputs  = jnp.array(inp_np)
        targets = jnp.array(out_np)

        state, loss = train_step(state, inputs, targets)

        if step % eval_every == 0:
            loss_val = float(loss)
            elapsed  = time.time() - t0
            print(f"  step {step:6d}/{steps}  loss={loss_val:.6f}  "
                  f"lr={float(schedule(step)):.2e}  elapsed={elapsed:.1f}s")

            if loss_val < best_loss:
                best_loss = loss_val
                checkpointer.save(str(ckpt_dir / "fluid_best"),
                                  args=ocp.args.StandardSave(state))

        if step % checkpoint_every == 0:
            checkpointer.save(str(ckpt_dir / f"fluid_step{step:07d}"),
                              args=ocp.args.StandardSave(state))

    print(f"Training complete. Best loss: {best_loss:.6f}")
    export_onnx(state.params, model, grid_size, out_dir)


# ─── ONNX Export ─────────────────────────────────────────────────────────────

def export_onnx(params, model: FNOFluid3D, grid_size: int, out_dir: str) -> str:
    """Export FNOFluid3D to bifrost_fluid.onnx.

    Output tensor contract (must match BIFROSTModelRegistry ModelSpec(8, 4)):
      Input:  float32 [1, N, N, N, 8]
      Output: float32 [1, N, N, N, 4]
    """
    try:
        import torch
        import torch.onnx
        from jax.experimental import jax2torch
    except ImportError:
        print("[WARN] PyTorch not available; trying jax2tf + tf2onnx path")
        return _export_via_tf(params, model, grid_size, out_dir)

    out_path = Path(out_dir) / "bifrost_fluid.onnx"
    out_path.parent.mkdir(parents=True, exist_ok=True)

    # Convert JAX → PyTorch via jax2torch (experimental)
    dummy_np = np.zeros((1, grid_size, grid_size, grid_size, 8), dtype=np.float32)
    dummy_jax = jnp.array(dummy_np)

    def jax_forward(x):
        return model.apply({'params': params}, x)

    torch_fn = jax2torch.jax2torch(jax_forward)
    dummy_torch = torch.from_numpy(dummy_np)

    torch.onnx.export(
        torch_fn,
        (dummy_torch,),
        str(out_path),
        input_names  = ["input"],
        output_names = ["output"],
        dynamic_axes = {},           # fixed N, batch=1
        opset_version = 17,
    )
    print(f"Exported: {out_path}  (input [1,{grid_size},{grid_size},{grid_size},8])")
    return str(out_path)


def _export_via_tf(params, model, grid_size: int, out_dir: str) -> str:
    """Fallback export via jax2tf + tf2onnx."""
    try:
        import tensorflow as tf
        from jax.experimental import jax2tf
        import tf2onnx
    except ImportError as e:
        raise RuntimeError(
            "Neither PyTorch nor (TensorFlow + tf2onnx) is available. "
            "Install one of them to enable ONNX export.") from e

    out_path = Path(out_dir) / "bifrost_fluid.onnx"
    dummy = np.zeros((1, grid_size, grid_size, grid_size, 8), dtype=np.float32)

    tf_fn = tf.function(
        jax2tf.convert(lambda x: model.apply({'params': params}, x),
                       enable_xla=False),
        input_signature=[tf.TensorSpec(dummy.shape, tf.float32, name="input")])

    model_proto, _ = tf2onnx.convert.from_function(
        tf_fn,
        input_signature=[tf.TensorSpec(dummy.shape, tf.float32, name="input")],
        output_path=str(out_path),
        opset=17)

    print(f"Exported (tf2onnx): {out_path}")
    return str(out_path)


# ─── CLI ─────────────────────────────────────────────────────────────────────

def main():
    parser = argparse.ArgumentParser(
        description="Train FNOFluid3D and export bifrost_fluid.onnx")
    parser.add_argument("--data-dir",   default="./data/fluid",
                        help="Directory with fluid_traj_shard_*.npz from ns_reference_solver")
    parser.add_argument("--out-dir",    default="./output/fluid",
                        help="Output directory for checkpoints and .onnx")
    parser.add_argument("--steps",      type=int, default=100_000)
    parser.add_argument("--lr",         type=float, default=DEFAULT_LR)
    parser.add_argument("--grid-size",  type=int,   default=GRID_SIZE,
                        help="Sub-cell grid N (must match ns_reference_solver --grid-size)")
    parser.add_argument("--seed",       type=int,   default=42)
    parser.add_argument("--fast",       action="store_true",
                        help="Reduce to 20k steps with larger LR for quick smoke-test")
    parser.add_argument("--export-only", action="store_true",
                        help="Skip training, load best checkpoint and export ONNX")
    parser.add_argument("--ckpt",       default=None,
                        help="Checkpoint path for --export-only")
    args = parser.parse_args()

    if args.fast:
        args.steps = 20_000
        args.lr    = 3e-3

    if args.export_only:
        if not _FULL_DEPS:
            raise ImportError("JAX/Flax required for export.")
        if args.ckpt is None:
            args.ckpt = os.path.join(args.out_dir, "checkpoints", "fluid_best")
        model = FNOFluid3D()
        checkpointer = ocp.StandardCheckpointer()
        state = checkpointer.restore(args.ckpt)
        export_onnx(state.params, model, args.grid_size, args.out_dir)
    else:
        train(args.data_dir, args.steps, args.out_dir,
              lr=args.lr, grid_size=args.grid_size, seed=args.seed)


if __name__ == "__main__":
    main()
