"""Adaptive SSGO — SSGO with dynamically generated spectral weights from HyperNet.

Literature design:
- Additive residual weights: W = W_base + alpha*DeltaW(z)
  (Ortiz et al. latent-space hypernetwork optimization)
- Low-rank CP decomposition for DeltaW to avoid parameter explosion
  (HypeMeFed + Low-rank HyperPINN)
- Spectral normalization on HyperNet backbone for training stability
  (hyperFastRL / Miyato 2018)
"""
from __future__ import annotations

from typing import Sequence

import jax
import jax.numpy as jnp
import flax.linen as nn

from hybr.core.geometry_encoder import SpectralGeometryEncoder
from hybr.core.hypernet import HyperMLP, SpectralWeightHead, PerNeuronScaleHead
from hybr.core.weight_bank import SpectralWeightBank, BiasBank


class AdaptiveWeightedSpectralConv3D(nn.Module):
    """Spectral conv whose weights come from a WeightBank (base + hypernet delta)."""

    in_channels: int
    out_channels: int
    modes: int = 8

    @nn.compact
    def __call__(
        self,
        x: jnp.ndarray,
        weights: jnp.ndarray,  # complex [B, C_in, C_out, mx, my, mz]
        mode_w: jnp.ndarray,   # [B, mx, my, mz]
    ) -> jnp.ndarray:
        B, Lx, Ly, Lz, _ = x.shape
        mx = min(self.modes, Lx)
        my = min(self.modes, Ly)
        mz = min(self.modes, Lz // 2 + 1)

        x_ft = jnp.fft.rfftn(x, axes=(1, 2, 3))
        x_modes = x_ft[:, :mx, :my, :mz, :]
        # weights shape already matches after materialization
        out_modes = jnp.einsum("bxyzi,bioxyz->bxyzo", x_modes, weights * mode_w[:, None, None, :, :, :])

        out_ft = jnp.zeros((B, Lx, Ly, Lz // 2 + 1, self.out_channels), dtype=jnp.complex64)
        out_ft = out_ft.at[:, :mx, :my, :mz, :].set(out_modes)
        return jnp.fft.irfftn(out_ft, s=(Lx, Ly, Lz), axes=(1, 2, 3)).real


class AdaptiveFNOBlock(nn.Module):
    """FNO block using externally supplied spectral weights."""

    channels: int
    modes: int = 8

    @nn.compact
    def __call__(
        self,
        x: jnp.ndarray,
        spectral_weights: jnp.ndarray,  # complex [B, C, C, mx, my, mz]
        mode_w: jnp.ndarray,
    ) -> jnp.ndarray:
        x_spec = AdaptiveWeightedSpectralConv3D(
            in_channels=self.channels,
            out_channels=self.channels,
            modes=self.modes,
        )(x, spectral_weights, mode_w)
        x_local = nn.Dense(self.channels)(x)
        return nn.gelu(x_spec + x_local)


class AdaptiveSSGO(nn.Module):
    """SSGO where all FNO spectral weights are generated by a HyperNet conditioned on geometry.

    Args:
        hidden: channels width
        modes: FNO frequency modes
        n_global_layers: number of global FNO blocks
        n_backbone_layers: number of backbone FNO blocks
        latent_dim: dimension of geometry encoder output
        hypernet_widths: MLP widths for HyperNet backbone
        rank: CP rank for low-rank weight generation
        encoder_type: "spectral" or "cnn"
    """

    hidden: int = 48
    modes: int = 6
    n_global_layers: int = 3
    n_focal_layers: int = 2
    n_backbone_layers: int = 2
    moe_hidden: int = 32
    latent_dim: int = 32
    hypernet_widths: Sequence[int] = (128, 128)
    rank: int = 2
    encoder_type: str = "spectral"

    @nn.compact
    def __call__(self, x: jnp.ndarray, update_stats: bool = True) -> jnp.ndarray:
        """
        Args:
            x: [B, L, L, L, 6]  (occ, E_norm, nu, rho_norm, rcomp_norm, rtens_norm)
            update_stats: passed to SpectralNorm layers during training
        Returns:
            [B, L, L, L, 10]
        """
        occ = x[..., 0:1]  # [B, L, L, L, 1]
        occ_squeezed = occ.squeeze(-1)  # [B, L, L, L]

        # ── Geometry Encoder ──
        if self.encoder_type == "spectral":
            z = SpectralGeometryEncoder(self.latent_dim)(occ_squeezed)
        else:
            from hybr.core.geometry_encoder import LightweightCNNEncoder
            z = LightweightCNNEncoder(self.latent_dim)(occ_squeezed)

        # ── HyperNet Backbone ──
        hyper_features = HyperMLP(
            hidden_widths=self.hypernet_widths,
            latent_dim=self.latent_dim,
        )(z, update_stats=update_stats)

        # ── Weight Generation Helpers ──
        L = x.shape[1]
        mx = min(self.modes, L)
        my = min(self.modes, L)
        mz = min(self.modes, L // 2 + 1)

        def make_spectral_weights() -> tuple:
            """Generate one set of adaptive spectral weights (real + imag)."""
            head_r = SpectralWeightHead(
                rank=self.rank,
                in_channels=self.hidden,
                out_channels=self.hidden,
                mx=mx, my=my, mz=mz,
                generate_mode_w=True,
            )
            head_i = SpectralWeightHead(
                rank=self.rank,
                in_channels=self.hidden,
                out_channels=self.hidden,
                mx=mx, my=my, mz=mz,
                generate_mode_w=False,
            )
            cp_r = head_r(hyper_features)
            cp_i = head_i(hyper_features)
            mode_delta = cp_r.pop("mode_w_delta")
            weights, mode_w = SpectralWeightBank(
                in_channels=self.hidden,
                out_channels=self.hidden,
                mx=mx, my=my, mz=mz,
            )(cp_r, cp_i, mode_delta)
            return weights, mode_w

        # ── Global Branch ──
        g = nn.Dense(self.hidden)(x)
        for _ in range(self.n_global_layers):
            w, mw = make_spectral_weights()
            g = AdaptiveFNOBlock(self.hidden, self.modes)(g, w, mw)

        # ── Focal Branch ──
        from brnext.models.voxel_gat import SparseVoxelGraphConv
        f = nn.Dense(self.hidden)(x)
        for _ in range(self.n_focal_layers):
            f = SparseVoxelGraphConv(self.hidden)(f, occ_squeezed)

        # ── Gated Fusion ──
        concat = jnp.concatenate([g, f], axis=-1)
        gate = jax.nn.sigmoid(nn.Dense(1)(concat))
        fused = gate * g + (1.0 - gate) * f

        # ── Shared Backbone ──
        h = fused
        for _ in range(self.n_backbone_layers):
            w, mw = make_spectral_weights()
            h = AdaptiveFNOBlock(self.hidden, self.modes)(h, w, mw)

        # ── MoE-Spectral Head ──
        from brnext.models.moe_head import MoESpectralHead
        moe_out = MoESpectralHead(out_channels=self.hidden, hidden=self.moe_hidden)(h)

        # ── Task Heads ──
        head_w = max(self.hidden, 32)

        s = nn.Dense(head_w)(moe_out)
        s = nn.gelu(s)
        stress = nn.Dense(6)(s)

        d = nn.Dense(head_w)(moe_out)
        d = nn.gelu(d)
        disp = nn.Dense(3)(d)

        p = nn.Dense(head_w)(moe_out)
        p = nn.gelu(p)
        phi = nn.Dense(1)(p)

        out = jnp.concatenate([stress, disp, phi], axis=-1)
        return out * occ
